apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/fluxcd/kustomize-controller/v1beta2/config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
- https://github.com/fluxcd/kustomize-controller/releases/download/v0.14.1/kustomize-controller.deployment.yaml
- account.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: kustomize-controller
  path: patch.yaml
images:
  - name: fluxcd/kustomize-controller
    newName: fluxcd/kustomize-controller
    newTag: v1beta2-50c71354
